<?php
/**
 * CustomValidationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Yext\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Yext API
 *
 * 
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Yext\Client;

/**
 * CustomValidationTest Class Doc Comment
 *
 * @category    Class */
// * @description A Custom Field validation object, describing validation rules when a Custom Field value is set or updated.
/**
 * @package     Yext\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CustomValidationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "CustomValidation"
     */
    public function testCustomValidation()
    {

    }

    /**
     * Test attribute "max_date"
     */
    public function testPropertyMaxDate()
    {

    }

    /**
     * Test attribute "min_height"
     */
    public function testPropertyMinHeight()
    {

    }

    /**
     * Test attribute "max_value"
     */
    public function testPropertyMaxValue()
    {

    }

    /**
     * Test attribute "min_value"
     */
    public function testPropertyMinValue()
    {

    }

    /**
     * Test attribute "min_width"
     */
    public function testPropertyMinWidth()
    {

    }

    /**
     * Test attribute "min_char_length"
     */
    public function testPropertyMinCharLength()
    {

    }

    /**
     * Test attribute "max_item_count"
     */
    public function testPropertyMaxItemCount()
    {

    }

    /**
     * Test attribute "min_item_count"
     */
    public function testPropertyMinItemCount()
    {

    }

    /**
     * Test attribute "max_char_length"
     */
    public function testPropertyMaxCharLength()
    {

    }

    /**
     * Test attribute "aspect_ratio"
     */
    public function testPropertyAspectRatio()
    {

    }

    /**
     * Test attribute "min_date"
     */
    public function testPropertyMinDate()
    {

    }

}
